# Site settings
title:          shell-snippets
description:    "snippets, notes and chemical X"
baseurl:        ""
url:            ""

# https://jekyllrb.com/docs/configuration/options/
timezone: Asia/Kolkata

header_pages:
  - index.md

listen_for_clients_preferred_style: true

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true