# Site settings
title:          snippet-diary
description:    "notes about code, setups, workflow and why your favorite editor is the best one ever"
baseurl:        "/snippet-diary"
url:            ""

# https://jekyllrb.com/docs/configuration/options/
timezone: Asia/Kolkata

header_pages:
  - index.md

# Available style options based on catppuccin: latte, frappe, macchiato, mocha
style_light: latte 
style_dark: macchiato


plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge